extern	void 	straightcopy( int copyWidth, BYTE *dest, BYTE *srce );
extern	void  flipsprcopy(int copyWidth, BYTE *dest, BYTE *srce);
extern	void 	spritecopy( int copyWidth, BYTE *dest, BYTE *srce );
extern	void 	spriteinccopy( int copyWidth, BYTE *dest, BYTE *srce );
extern	void 	spriteareainccopy(int copyWidth, BYTE *dest, BYTE *srce);
extern	void 	pseudostore(int copyWidth, BYTE *dest, BYTE *srce);
extern	void 	spritefilter(int copyWidth, BYTE *dest, BYTE *srce);
typedef  void 	(*copyfunctiontype)( int copyWidth, BYTE *srce, BYTE *dest );
extern	void 	DrawIMAGE( pseudo_info *, texture_info *, int, int, int, signed char, copyfunctiontype );
extern	void 	StorePSEUDObuffer( pseudo_info *, texture_info *, int, int, int );
extern	void 	CopyFromBACKtoPSEUDObuffer( pseudo_info *, pseudo_info *, int, int, short, short );
extern	int	PixelLengthOfString( char *, int );
extern	void	DisplayString( int, int, char *, int, int, signed char, pseudo_info *, texture_info * );
extern	void 	CreateFilter( BYTE *, char, char, char, float, float, float );
extern	void	ControlAnimations();
extern	void	CopyDumpListToScreen();
extern	void	AddToDumpList( short, short, short, short );
extern	void	ClearDumpList();
extern	void	DisplayBackground( int );
extern	char	LeagueColourOffsets[];
extern	void	Set_palette_to_black();
extern	short	ControlSlider( slider_info *, short, short, short );
extern	void 	DisplayTextInputCursor( char *, short );
extern	void	Set_640x480_VideoMode();
extern	void	Test_640x480_VideoMode();
extern	char	ControlOptionHighlight( signed char, signed char, signed char, char, short, short );
extern	char	*GetTEAMname( char, char );
extern	char	*StringTemplete( short, char );
extern	char	*LowerCaseString( char * );

