extern	char	*ToUPPER( char * );
// extern	char	*GetTEAMname( char, char );
extern	void 	DisplayTextInputCursor( int, short, int, char *, int, int, pseudo_info *, texture_info * );
extern	void  InitialiseMenuPage( char );
extern	void	OverlayStaticBackgroundImages( char  );
extern	void	SetupExtraTexturePages( int );
extern	void	ControlPalette( BYTE * );
extern	char	*GetPLAYERSname( char, char, char );
extern	void	__far EUROinterupt(void);
extern	void	ResetAnimations();
extern	short	AddAnimation( int, int, float, float, float, signed char, signed char );
extern	void	ResetBoundingBoxes();
extern	signed char GetBoundingBox( short, short );
extern	void	DisplayCountrySelectImages();
extern	void 	DoMainScreen( char );
extern	void	DisplayBoundingBoxes();
extern	void 	StartingEURO_96( char );
extern	void 	InitEUROrand();
extern	short EuroRandomze();
extern	char	ConfigureTeamView();
