extern	short	DisplayModemSetupPanel();
extern	void	DoModemSetup( char, signed char );
extern	void	DisplayModemSettings();
extern	void	DisplayDialSetting();
extern	void	DisplayCommSetting();
extern	void	DisplayModemType();
extern	void	InitialiseInitString( signed short );
extern	void	DisplayInitString();
extern	void	DisplayTelephoneNumber();
extern	void	DisplayModemList( char );
