extern	signed int			 	restore_cup_data[];
extern	restore_data			restore_league_data[];
extern	redefine_info			redefine_data[];
extern	team_info				game_data[];
//	extern	team_formation			formation_data[];
extern	swap_player_buffer	swap_buffer[];
// old actua	extern	sprite					sprite_table[];
// old actua	extern	sprite					sprite_table_small[];
extern	int						spin_y_offsets[];
// old actua	extern	long						spool_index[];
// old actua	extern	long						spool_index_small[];
// old actua	extern	char						*formation_types[];
// old actua	extern	char						*sky_types[];
// old actua	extern	char						*stadium_types[];
// old actua	extern	char						*pitch_types[];
// old actua	extern	char						*camera_types[];
// old actua	extern	char						*size_types[];
// old actua	extern	char						*audio_types[];
// old actua	extern	char						*NETWORK_types[];
extern	referee_info			referee_data[];
// old actua	extern	char						*slot_names[];
extern	int						network_referee[];
// old actua	extern	menu						menu_data[];
extern	label						menu_labels[];
extern	image						menu_images[];
extern	detail_info 			detail_defaults[];
extern	short 					screen_defaults[];
// old actua	extern	char						*NoOfPLAYERS_types[];
// old actua	extern	char						*Game_types[];
// old actua	extern	char						*COMPETITION_types[];
// old actuaextern	choose_info				choose_data[];
// old actua	extern	char						*VENUES[];
// old actuaextern	controls   				control_table[];
extern	char						friendly_controls[];
// old actua	extern	char						*time_types[];
// old actua	extern	char						*calibrate_message[];
// old actua	extern	char						*redefine_message[];

extern	setup_info				setup;
extern	match_data				match_info;

// old actua	extern	int						allocation_flags[];
// old actua	extern	fixture_table			fixtures[];
extern	int						cup_games[];
// old actua	extern	char						*ROUNDS[];
// old actua	extern	char						*player_labels[];
// old actua	extern	char						*control_labels[];
// old actuaextern	int						team_b_kit[];
// old actua	extern	char						*wind_types[];
extern	goal_table				goals[];
extern	result_table			results[];
extern	batch_data				batch_info;
// old actuaextern	short						LegalKEY[];
// old actuaextern	char					   *KEYtext[];
// old actuaextern	int						copykeys[];
// old actua	extern	char						*sub_types[];
					  	
extern	int						GDVvidmode[];
extern	int						MENUvidmode[];
extern	int						RESTOREvidmode[];
// old actua	extern	char						*FrenchCountryNames[];
// old actua	extern	char						*FrenchNickNames[];
// old actua	extern	char						*GermanTeamNames[];
// old actua	extern	char						*GermanCountryNames[];
// old actua	extern	char						*GermanNickNames[];
// old actua	extern	char						*NorwegianCountryNames[];
// old actua	extern	char						*NorwegianNickNames[];

extern	demo_struct				demo_data[];
// old actua	extern	char						CodeWheelNumbers[];
// old actua	extern	char						CodeWheelWindows[];
// old actua	extern	char						CodeWheelWindowsOffs[];
// old actua	extern	german_manual			manual[];
